"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import { apiRequest, type Overview } from "@/lib/api";

export default function OverviewPage(){const {id}=useParams<{id:string}>();const [data,setData]=useState<Overview|null>(null);const [error,setError]=useState("");
 useEffect(()=>{apiRequest<Overview>(`/intelligence/${id}`).then(setData).catch(e=>{setError(e.message??"Could not load this overview.");});},[id]);
 if(error)return <main className="grid min-h-screen place-items-center bg-slate-50"><div className="rounded-2xl border bg-white p-8"><p role="alert">{error}</p><Link className="mt-4 inline-block text-indigo-700 underline" href="/dashboard">Back to repositories</Link></div></main>;
 if(!data)return <main className="min-h-screen bg-slate-50 p-10"><div role="status" className="mx-auto max-w-5xl rounded-2xl border bg-white p-8">Loading repository overview…</div></main>;
 const repo=data.repository;const structural=data.structural_data;
 return <main className="min-h-screen bg-slate-50"><header className="border-b bg-white"><nav className="mx-auto flex h-16 max-w-6xl items-center justify-between px-6"><Link href="/dashboard" className="font-semibold">RepoLens</Link><Link href="/dashboard" className="text-sm text-slate-600 hover:text-slate-950">All repositories</Link></nav></header><section className="mx-auto max-w-6xl px-6 py-10"><p className="text-xs font-semibold uppercase tracking-[.2em] text-indigo-700">Repository Overview</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">{repo.owner} / {repo.name}</h1><p className="mt-3 text-slate-600">{repo.description||"No repository description provided."}</p><p className="mt-3 break-all font-mono text-xs text-slate-500">Analyzed commit {repo.commit_sha}</p>
 <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Primary language",repo.primary_language??"Unknown"],["Tracked files",repo.file_count?.toLocaleString()??"Unknown"],["Repository size",repo.size_kb==null?"Unknown":`${repo.size_kb.toLocaleString()} KB`],["Modules","Not implemented yet"]].map(([label,value])=><div key={label} className="rounded-2xl border bg-white p-5"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-xl font-semibold">{value}</p></div>)}</div>
 <div className="mt-6 grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border bg-white p-6"><h2 className="font-semibold">Technology stack</h2>{repo.technologies.length?<div className="mt-4 flex flex-wrap gap-2">{repo.technologies.map(x=><span key={x} className="rounded-full bg-indigo-50 px-3 py-1.5 text-sm font-medium text-indigo-700">{x}</span>)}</div>:<p className="mt-3 text-sm text-slate-500">No recognized framework or technology evidence was found in the repository manifests.</p>}<h3 className="mt-6 text-sm font-semibold">Language breakdown</h3>{repo.language_breakdown&&Object.keys(repo.language_breakdown).length?<ul className="mt-3 space-y-2">{Object.entries(repo.language_breakdown).sort((a,b)=>b[1]-a[1]).map(([name,bytes])=><li key={name} className="flex justify-between text-sm"><span>{name}</span><span className="text-slate-500">{(bytes/1024).toFixed(1)} KB</span></li>)}</ul>:<p className="mt-2 text-sm text-slate-500">Language breakdown unavailable.</p>}</section>
 <section className="rounded-2xl border bg-white p-6"><h2 className="font-semibold">Executive summary</h2><p className="mt-3 text-sm leading-6 text-slate-600">{data.summary??"A generated executive summary is not part of this release. This overview shows deterministic metadata extracted from the repository."}</p><h3 className="mt-6 text-sm font-semibold">Detected entry points</h3>{repo.entry_points.length?<ul className="mt-3 space-y-2">{repo.entry_points.map(path=><li key={path} className="rounded-lg bg-slate-50 px-3 py-2 font-mono text-xs">{path}</li>)}</ul>:<p className="mt-2 text-sm text-slate-500">No deterministic entry point was identified.</p>}</section></div>
 <section className="mt-6 rounded-2xl border bg-white p-6"><h2 className="font-semibold">Structural metadata</h2><p className="mt-1 text-sm text-slate-500">Tree-sitter parsed repository declarations; repository code was never executed.</p><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Parsed files",structural?.parsed_file_count??0],["Symbols",structural?.symbol_count??0],["Imports and exports",structural?.import_count??0],["Parse errors",structural?.parse_error_count??0]].map(([label,value])=><div key={label} className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 font-semibold">{value}</p></div>)}</div><div className="mt-5 grid gap-6 lg:grid-cols-2"><div><h3 className="text-sm font-semibold">Declarations</h3><ul className="mt-2 max-h-80 space-y-2 overflow-auto">{(structural?.symbols??[]).slice(0,100).map((symbol,i)=><li key={`${symbol.path}:${symbol.start_line}:${i}`} className="rounded-lg border border-slate-100 p-3"><p className="text-sm font-medium">{symbol.name} <span className="text-xs font-normal text-slate-500">{symbol.kind}</span></p><p className="mt-1 truncate font-mono text-xs text-slate-500">{symbol.path}:{symbol.start_line}</p>{symbol.docstring&&<p className="mt-2 text-xs text-slate-600">{symbol.docstring}</p>}</li>)}</ul></div><div><h3 className="text-sm font-semibold">Imports and exports</h3><ul className="mt-2 max-h-80 space-y-2 overflow-auto">{(structural?.imports??[]).slice(0,100).map((item,i)=><li key={`${item.path}:${item.line}:${i}`} className="rounded-lg bg-slate-50 p-3"><p className="truncate font-mono text-xs">{item.declaration}</p><p className="mt-1 truncate text-xs text-slate-500">{item.path}:{item.line}</p></li>)}</ul></div></div></section>
 <p className="mt-5 text-xs text-slate-500">Default branch: {repo.default_branch??"Unknown"} · Last analyzed: {repo.analyzed_at?new Date(repo.analyzed_at).toLocaleString():"Unknown"} · Stages 5–7 (modules, deeper intelligence, and generated insights) are deferred.</p></section></main>;
}
