"use client";

import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { apiRequest, type AnalysisStatus } from "@/lib/api";

const stages=["Cloning repository","Detecting technologies","Parsing source code","Extracting metadata","Detecting modules","Building intelligence","Generating insights","Preparing dashboard"];
export default function AnalysisPage(){const params=useParams<{id:string}>();const router=useRouter();const [data,setData]=useState<AnalysisStatus|null>(null);const [error,setError]=useState("");
 useEffect(()=>{let active=true;let timer:ReturnType<typeof setTimeout>;const poll=async()=>{try{const result=await apiRequest<AnalysisStatus>(`/analysis/${params.id}/status`);if(!active)return;setData(result);if(result.status==="COMPLETED"){router.replace(`/repositories/${result.repository_id}`);return;}if(result.status==="FAILED"){setError(result.failure?.message??"Analysis failed. Please return to repository selection and try again.");return;}}catch(e){if(active)setError(e instanceof Error?e.message:"Analysis status could not be loaded.");return;}timer=setTimeout(poll,2000);};void poll();return()=>{active=false;clearTimeout(timer);};},[params.id,router]);
 return <main className="min-h-screen bg-slate-50"><header className="border-b bg-white"><nav className="mx-auto flex h-16 max-w-5xl items-center px-6"><Link href="/dashboard" className="font-semibold">RepoLens</Link></nav></header><section className="mx-auto max-w-3xl px-6 py-16"><p className="text-xs font-semibold uppercase tracking-[.2em] text-indigo-700">Repository analysis</p><h1 className="mt-2 text-3xl font-semibold">Building your overview</h1><p className="mt-3 text-slate-600">This runs in the background. You can keep this page open while RepoLens prepares repository metadata and semantic search.</p>{error?<div role="alert" className="mt-8 rounded-xl border border-rose-200 bg-rose-50 p-5 text-rose-900"><p className="font-medium">Analysis could not be completed</p><p className="mt-2 text-sm">{error}</p><Link className="mt-4 inline-block text-sm font-semibold underline" href="/dashboard">Back to repositories</Link></div>:<div className="mt-8 rounded-2xl border bg-white p-6"><div className="flex justify-between text-sm"><span>{data?.stage??"QUEUED"}</span><span>{data?.progress??0}%</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-indigo-600 transition-all" style={{width:`${data?.progress??0}%`}}/></div><ol className="mt-7 space-y-3">{stages.map((stage,i)=>{const completed=data?.completed_stages.includes(stage)??false;const current=data?.stage===stage;const deferred=data?.deferred_stages.includes(stage)??false;return <li key={stage} className="flex items-center gap-3 text-sm"><span className={`grid size-6 place-items-center rounded-full text-xs ${completed?"bg-emerald-100 text-emerald-700":current?"bg-indigo-100 text-indigo-700":"bg-slate-100 text-slate-500"}`}>{completed?"✓":i+1}</span><span className={completed||current?"font-medium":"text-slate-500"}>{stage}</span>{deferred&&<span className="ml-auto rounded-full bg-slate-100 px-2 py-1 text-xs text-slate-500">Not in this release</span>}</li>;})}</ol><p className="mt-6 border-t pt-4 text-xs leading-5 text-slate-500">RepoLens builds semantic chunks and embeddings during Stage 6. Generating insights (Stage 7) is deferred; dashboard preparation follows.</p></div>}</section></main>;
}
